/*Login*/
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

/*Logout*/
export const AUTH_LOTOUT = "AUTH_LOGOUT";
/*Register*/
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

/*MEMO*/
export const MEMO_POST  = "MEMO_POST";
export const MEMO_POST_SUCCESS = "MEMO_SUCCESS";
export const MEMO_POST_FAILURE = "MEMO_FAILURE";


/*LIST*/

export const MEMO_LIST = "MEMO_LIST";
export const MEMO_LIST_SUCCESS = "MEMO_LIST_SUCCESS";
export const MEMO_LIST_FAILURE = "MEMO_LIST_FAILURE";
